############# English navigation ##############

# main menu
# [[main]]
# name = "About"
# pageRef = "/about"
# weight = 1


# [[main]]
# name = "Blog"
# pageRef = "/blog"
# weight = 2

# [[main]]
# name = "Contact"
# pageRef = "/contact"
# weight = 2

# footer menu
# [[footer]]
# name = "About"
# pageRef = "/about"
# weight = 1

[[footer]]
name = "Contact"
pageRef = "/contact"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
