############# English navigation ##############

# main menu
[[main]]
name = "Blog"
pageRef = "/"
weight = 1




[[main]]
name = "About"
pageRef = "/about"
weight = 2





# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1


[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
