############# English navigation ##############

# main menu
[[main]]
name = "My Notes"
pageRef = "/blog"
weight = 1

[[main]]
name = "About Me"
pageRef = "/about"
weight = 2

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
